spring.application.name=spring-reactive-mongo
spring.docker.compose.enabled=true

spring.data.mongodb.uri=mongodb://root:password@localhost:27017/admin

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000
